name: TruffleHog Scan on Push and PB

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  trufflehog:
    uses: futurewhitehat/secret-scanning-poc-1/.github/workflows/trufflehog-scan-reusable.yml@main
    with:
      base-ref: ${{ github.event.pull_request.base.sha || github.event.before }}
      head-ref: ${{ github.event.pull_request.head.sha || github.sha }}
      is-pr: ${{ github.event_name == 'pull_request' }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

