name: Call TruffleHog PR Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trufflehog-scan:
    uses: futuat/secret-c-1/.github/workflows/trufflehog_pr_scan.yml@main
    with:
      base-ref: ${{ github.base_ref }}
      head-ref: ${{ github.head_ref }}
      fail-on-secrets: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
