name: Example - Use TruffleHog Reusable Workflow

# This is an example of how to use the reusable TruffleHog workflow
# You can copy this to other repositories and customize as needed

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  secret-scanning:
    name: Secret Scanning
    uses: https://github.com/futurewhitehat/secret-scanning-poc/.github/workflows/trufflehog-scan-reusable.yml
    with:
      base-ref: 'main'                    # Branch to compare against
      head-ref: 'HEAD'                    # Current commit to scan
      fail-on-secrets: true               # Fail the workflow if secrets are found
      scan-depth: '50'                    # Number of commits to scan
      # config-path: '.trufflehog.yml'    # Optional: path to TruffleHog config
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Example: Use in a different configuration for different scenarios
  secret-scanning-warn-only:
    name: Secret Scanning (Warning Only)
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/trufflehog-scan-reusable.yml
    with:
      base-ref: 'main'
      head-ref: 'HEAD'
      fail-on-secrets: false              # Only warn, don't fail
      scan-depth: '100'                   # Deeper scan for manual runs
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

