name: Call TruffleHog PR Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:  # 👈 Add this block
  contents: read
  pull-requests: write    

jobs:
  trufflehog-scan:
    uses: futurewhitehat/secret-scanning-poc-1/.github/workflows/trufflehog-scan-reusable.yml@main
    with:
      base-ref: ${{ github.base_ref }}
      head-ref: ${{ github.head_ref }}
      fail-on-secrets: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
